version: 2

updates:
  - package-ecosystem: uv
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
