repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [ --fix ]

      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.392
    hooks:
      - id: pyright
