version: "3.8"

services:
  bot:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - edgedb
    restart: unless-stopped

  edgedb:
    image: edgedb/edgedb
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    volumes:
      - "./database/schema:/dbschema:ro"
    ports:
      - "5656:5656"
