version: "3.8"

services:
  bot:
    build:
      dockerfile: ./src/bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - edgedb
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  daemon:
    build:
      dockerfile: ./src/daemon/Dockerfile
    env_file:
      - .env
    depends_on:
      - edgedb
    restart: unless-stopped

  edgedb:
    image: edgedb/edgedb
    container_name: edgedb
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    volumes:
      - "./database/schema:/dbschema:ro"
      - edgedb_data:/var/lib/edgedb/data
    ports:
      - "5656:5656"

volumes:
  edgedb_data:
