# AUTOGENERATED FROM 'database/queries/lecturer/select_by_schema_id.edgeql' WITH:
#     $ edgedb-py --dir database/queries --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid

import edgedb


@dataclasses.dataclass
class SelectBySchemaIdResult:
    schema_id: int
    name: str
    full_name: str
    id: uuid.UUID


async def select_by_schema_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    schema_id: int,
) -> list[SelectBySchemaIdResult]:
    return await executor.query(
        """\
        select (Lecturer) {*} filter { .schema_id = <int16>$schema_id };\
        """,
        schema_id=schema_id,
    )
