# AUTOGENERATED FROM 'database/queries/couple/insert.edgeql' WITH:
#     $ edgedb-py --dir database/queries --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import datetime
import uuid

import edgedb


@dataclasses.dataclass
class InsertResult:
    id: uuid.UUID


async def insert(
    executor: edgedb.AsyncIOExecutor,
    *,
    break_time: int,
    number: int,
    time_start: datetime.datetime,
    time_end: datetime.datetime,
    lesson_ids: list[uuid.UUID],
) -> InsertResult:
    return await executor.query_single(
        """\
        insert Couple {
          break_time := <int16>$break_time,
          number := <int16>$number,
          time_start := <datetime>$time_start,
          time_end := <datetime>$time_end,
          lessons := (
            select (Lesson) filter { Lesson.id in array_unpack(<array<uuid>>$lesson_ids) }
          ),
        };\
        """,
        break_time=break_time,
        number=number,
        time_start=time_start,
        time_end=time_end,
        lesson_ids=lesson_ids,
    )
