"""add_area_to_group

Revision ID: 93970cc7758d
Revises: 8cf9b9e9da4b
Create Date: 2025-05-26 10:59:15.567348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93970cc7758d"
down_revision: Union[str, None] = "8cf9b9e9da4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column("area", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "area")
    # ### end Alembic commands ###
