"""unique lesson

Revision ID: 48d3baae21a0
Revises: e4fd50561fa1
Create Date: 2025-01-25 10:22:58.862358

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48d3baae21a0"
down_revision: Union[str, None] = "e4fd50561fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_lesson", "lesson", ["schedule_id", "time_slot_id", "subgroup"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_lesson", "lesson", type_="unique")
    # ### end Alembic commands ###
