"""update group.area type

Revision ID: 1630f1ec3d9c
Revises: 93970cc7758d
Create Date: 2025-05-26 11:22:09.092663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1630f1ec3d9c"
down_revision: Union[str, None] = "93970cc7758d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column("area_name", sa.String(), server_default=sa.text("text('ССО')"), nullable=False),
    )
    op.drop_column("group", "area")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column(
            "area", sa.INTEGER(), server_default=sa.text("1"), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("group", "area_name")
    # ### end Alembic commands ###
