"""fix(user_settings): unique user_id

Revision ID: f6a0a6a162ff
Revises: 1630f1ec3d9c
Create Date: 2026-02-16 00:52:46.258228

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6a0a6a162ff"
down_revision: Union[str, None] = "1630f1ec3d9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DELETE FROM user_settings
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM user_settings
            GROUP BY user_id
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_settings", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_settings", type_="unique")
    # ### end Alembic commands ###
