# AUTOGENERATED FROM 'database/queries/lesson/save_insert.edgeql' WITH:
#     $ edgedb-py --dir database/queries --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid

import edgedb


@dataclasses.dataclass
class SaveInsertResult:
    id: uuid.UUID


async def save_insert(
    executor: edgedb.AsyncIOExecutor,
    *,
    cabinet_id: int,
    lecturer_id: int,
) -> SaveInsertResult:
    return await executor.query_single(
        """\
        insert Lesson {
          cabinet := (select Cabinet filter .schema_id = <int16>$cabinet_id),
          lecturer := (select Lecturer filter .schema_id = <int16>$lecturer_id),
        };\
        """,
        cabinet_id=cabinet_id,
        lecturer_id=lecturer_id,
    )
