# AUTOGENERATED FROM 'database/queries/lesson/select_by_relations.edgeql' WITH:
#     $ edgedb-py --dir database/queries --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid

import edgedb


@dataclasses.dataclass
class SelectByRelationsResult:
    id: uuid.UUID
    cabinet: SelectByRelationsResultCabinet | None
    lecturer: SelectByRelationsResultLecturer | None


@dataclasses.dataclass
class SelectByRelationsResultCabinet:
    id: uuid.UUID
    number: str
    schema_id: int
    title: str


@dataclasses.dataclass
class SelectByRelationsResultLecturer:
    schema_id: int
    name: str
    full_name: str
    id: uuid.UUID


async def select_by_relations(
    executor: edgedb.AsyncIOExecutor,
    *,
    cabinet_id: int,
    lecturer_id: int,
) -> list[SelectByRelationsResult]:
    return await executor.query(
        """\
        select (Lesson) {**} filter
        .cabinet.schema_id = <int16>$cabinet_id
        and .lecturer.schema_id = <int16>$lecturer_id;\
        """,
        cabinet_id=cabinet_id,
        lecturer_id=lecturer_id,
    )
