# AUTOGENERATED FROM 'database/queries/lesson/select_by_id.edgeql' WITH:
#     $ edgedb-py --dir database/queries --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid

import edgedb


@dataclasses.dataclass
class SelectByIdResult:
    id: uuid.UUID


async def select_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> list[SelectByIdResult]:
    return await executor.query(
        """\
        select (Lesson) {*} filter { .id = <uuid>$id };\
        """,
        id=id,
    )
