name: Lint and check types

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        id: python-setup
        with:
          python-version: "3.11"
          cache: poetry

      - name: Set python version for poetry
        run: poetry env use 3.11

      - name: Validate the structure of the pyproject.toml
        run: poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        if: steps.python-setup.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Check code formatting by black
        run: poetry run black . --check

      - name: Run ruff
        run: poetry run ruff .

      - name: Check types by pyright
        run: poetry run pyright
