name: Lint and check types

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: yezz123/setup-uv@v4.1

      - name: Install dependencies
        run: make install

      - name: Check code linting
        run: make lint

      - name: Check code types
        run: make typecheck
